#!/bin/bash
#
# Prepares the "stack" to run apps and the environment to run buildpacks
#

#
# SYSTEM PACKAGES
#
yum -y update
xargs yum install -y --assumeyes < /build/packages.txt
yum groupinstall "Development Tools"
yum install -y curl-devel expat-devel gettext-devel openssl-devel zlib-devel gcc libyaml readline readline-devel php-pear php-xml unixODBC bzip2-devel 

cd /usr/local/src
wget https://www.kernel.org/pub/software/scm/git/git-1.8.3.4.tar.gz
tar xzvf git-1.8.3.4.tar.gz
cd git-1.8.3.4
export NO_PERL=1
make prefix=/usr/local all 
make prefix=/usr/local install

cd /usr/local/src
wget http://ftp.ruby-lang.org/pub/ruby/1.9/ruby-1.9.3-p545.tar.gz
tar xvzf ruby-1.9.3-p545.tar.gz
cd ruby-1.9.3-p545
./configure --prefix=/usr
make 
make install 

cd /usr/local/src
wget http://rubyforge.org/frs/download.php/76073/rubygems-1.8.24.tgz
tar xvzf rubygems-1.8.24.tgz
cd rubygems-1.8.24
ruby setup.rb
gem update --system

cd /
rm -rf /usr/local/src/*

cd /build/buildpacks/heroku-buildpack-php/
gem install bundler
bundle install

#
# SUPPORTED BUILDPACKS
#
mkdir -p /build/buildpacks
cd /build/buildpacks
export GIT_SSL_NO_VERIFY=true
xargs -L 1 git clone --depth=1 < /build/buildpacks.txt

#
# MISC
#

# Ruby buildpack system configuration
update-alternatives --set ruby /usr/bin/ruby1.9.1
update-alternatives --set gem /usr/bin/gem1.9.1
wget http://rubygems.org/downloads/bundler-1.6.1.gem
gem install bundler-1.6.1.gem
rm bundler-1.6.1.gem
